### ISSUE TITLE
Ética

### ISSUE THREAD

**Issue by MHatchikian** [Cristhhh/ISPC-Grupo-Booleano-#2]

**Comment by Cristhhh** [comment]
1. Enlace en la Wiki llamado Ética
   - **Conformación del grupo como instrumento legal**:
     - Describir cómo el grupo se estructura legalmente (empresa, socios, CEO, empleados) y las cláusulas que incluirá el contrato.

   - Matrícula profesional:
     - Describir quiénes deben matricularse y ante qué entidad provincial para ejercer la profesión.

   - Penalización por falta de matriculación:
     - Especificar la pena correspondiente a nivel provincial si un integrante no realiza el trámite de matriculación.

   - Divulgación de datos internos:
     - Describir las acciones legales que deben tomar los demás integrantes si uno divulga datos de la base de datos interna.

   - Reutilización del código para fines personales:
     - Describir las acciones legales según la Legislación de la Provincia de Córdoba y el Código Penal Argentino si un integrante reutiliza el código para fines personales.

   - Adulteración externa de la base de datos:
     - Indicar qué instrumento legal respalda a la empresa a nivel nacional en caso de adulteración externa de la base de datos.

   - Negligencia de los programadores:
     - Especificar el instrumento legal al que se acude y quién es responsable en caso de negligencia por parte de los programadores.

   - Reemplazo del sistema por otro proveedor:
     - Describir cómo actuar de manera ética ante el cliente y los colegas si el cliente decide reemplazar el sistema por otro proveedor.
